### ISSUE TITLE
I want to join your Discord

### ISSUE THREAD

**Issue by rjin315** [MarcosVLl2/NeoXtractor#4]
Hi, I wanted to join your discord to communicate with more people who use your program. If you don't mind, could you please update the discord link?

**Comment by MelancholySlime** [comment]
> Hi, I wanted to join your discord to communicate with more people who use your program. If you don't mind, could you please update the discord link?

https://discord.gg/eedXVqzmfn

**Comment by rjin315** [comment]
> > Hi, I wanted to join your discord to communicate with more people who use your program. If you don't mind, could you please update the discord link?
> 
> https://discord.gg/eedXVqzmfn

Thank you so much😁 Thank you for developing great tools
